const PDFDocument = require('pdfkit');

function generatePDF(document) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                margin: 72,
                size: 'A4',
                bufferPages: true
            });
            const buffers = [];
            
            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => resolve(Buffer.concat(buffers)));

            // Title Page
            doc.fontSize(24).font('Helvetica-Bold')
               .text(document.title || 'Legal Document', { align: 'center' });
            
            doc.moveDown(2);
            
            doc.fontSize(12).font('Helvetica')
               .text(`Date: ${new Date().toLocaleDateString('en-IN')}`, { align: 'center' });
               
            doc.moveDown(4);
            doc.fontSize(14).text('Generated by AI-Powered Legal Documentation Assistant', { align: 'center' });
            
            doc.addPage();
            
            // Body with pseudo-markdown handling
            const lines = (document.content || '').split('\n');
            let isBold = false;
            
            lines.forEach(line => {
                if (line.startsWith('# ')) {
                    doc.moveDown().fontSize(18).font('Helvetica-Bold').text(line.replace('# ', ''));
                } else if (line.startsWith('## ')) {
                    doc.moveDown().fontSize(14).font('Helvetica-Bold').text(line.replace('## ', ''));
                } else {
                    doc.fontSize(12).font('Helvetica').text(line, { align: 'justify' });
                }
            });

            // Add Header & Footer
            const pages = doc.bufferedPageRange();
            for (let i = 0; i < pages.count; i++) {
                doc.switchToPage(i);
                if (i > 0) { // No header on title page
                    doc.fontSize(10).font('Helvetica')
                       .text(document.title || 'Legal Document', 72, 40, { align: 'right' });
                }
                // Footer
                doc.fontSize(10).font('Helvetica')
                   .text(`Page ${i + 1} of ${pages.count}`, 72, doc.page.height - 50, { align: 'center' });
            }

            doc.end();
        } catch (error) {
            reject(error);
        }
    });
}

module.exports = { generatePDF };
